version: '3.9'
services:
  api:
    container_name: api
    env_file:
      - .env
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - .:/src
    depends_on:
      - db
    networks:
      - app_ntwrk

  db:
    image: postgres:latest
    container_name: db_container
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_ntwrk

volumes:
  pg_data:

# Networks to be created to facilitate communication between containers
networks:
  app_ntwrk:
    driver: bridge